### ISSUE TITLE
The company is a scam.

### ISSUE THREAD

**Issue by jasondrawdy** [BKWatch/CodingChallenge#123]
The company only has 1 star on Indeed and passes up on ideal candidates with the EXACT requirements for the job.

NOBODY SHOULD WORK FOR THEM!

**Comment by turkanis** [comment]
Hi Jason, 

Your submission was better than average, but there were a handful of candidates who did much better than you. Unfortunately, it is not feasible for me to schedule interviews with everyone who scores moderately well but not great.

Best Regards,
Jonathan Turkanis

P.S. We have several other stars, but they are currently being repaired
